### ISSUE TITLE
What is reference?

### ISSUE THREAD

**Issue by Shadowblitz16** [daniel-mcclintock/Octree.gd#4]
The type `Reference` doesn't exist.
Do you mean RefCounted?
```
class_name OctreeNode
extends RefCounted
```

**Comment by daniel-mcclintock** [comment]
Hi @Shadowblitz16,

This repo was created a fairly long time ago(~3 years ago) and hasn't been updated for recent Godot 4.x releases.

Back when this was created RefCounted was named Reference. It was later [renamed](https://github.com/godotengine/godot/pull/49312) to RefCounted.

If i can find some free time I may look into updating it(feel free to submit a PR if you get it working).

**Comment by Shadowblitz16** [comment]
oh ok ty
